apiVersion: v1
kind: Service
metadata:
    name: dubbo-samples-xds-consumer
    namespace: dubbo-demo
spec:
    clusterIP: None
    selector:
        app: dubbo-samples-xds-consumer
    ports:
        - name: grpc
          protocol: TCP
          port: 50051
          targetPort: 50051
---
apiVersion: v1
kind: Service
metadata:
    name: dubbo-samples-xds-provider
    namespace: dubbo-demo
spec:
    clusterIP: None
    selector:
        app: dubbo-samples-xds-provider
    ports:
        - name: grpc
          protocol: TCP
          port: 50051
          targetPort: 50051
        - name: meta
          protocol: TCP
          port: 20885
          targetPort: 20885
